import { CalendarDays, ChevronRight, Clock3, MapPin } from 'lucide-react';
import { Link, useNavigate } from 'react-router-dom';

const levels = ['Newbie', 'Beginner', 'Upper Beginner', 'Intermediate'];

export default function BookingPage() {
  const navigate = useNavigate();
  return <div className="booking-page"><header className="booking-nav"><Link className="home-brand" to="/"><span className="home-brand-mark"><i /></span><span><strong>rally</strong><small>COURT CLUB</small></span></Link><Link className="back-link" to="/dashboard">Back to dashboard <ChevronRight size={15} /></Link></header><main className="booking-content"><div className="booking-heading"><p className="home-kicker">Member booking</p><h1>Find your next<br /><em>coaching session.</em></h1><p>Choose a level and we will show you the best available classes.</p></div><section className="booking-panel"><div className="booking-panel-heading"><div><p className="eyebrow">Step 1 of 3</p><h2>What is your level?</h2></div><span className="booking-progress">● ○ ○</span></div><div className="level-grid">{levels.map((level, index) => <button className={`level-option ${index === 0 ? 'selected' : ''}`} key={level}><span>0{index + 1}</span><strong>{level}</strong><small>{index === 0 ? 'Start from the basics' : index === 1 ? 'Build your foundation' : index === 2 ? 'Play with intention' : 'Raise your level'}</small></button>)}</div><div className="booking-preview"><div><CalendarDays size={17} /><span>Next available<br /><strong>Tomorrow, 07:45</strong></span></div><div><Clock3 size={17} /><span>Duration<br /><strong>90 minutes</strong></span></div><div><MapPin size={17} /><span>Location<br /><strong>Rally Court Club</strong></span></div><button className="home-cta" onClick={() => navigate('/dashboard')}>See available classes <ChevronRight size={15} /></button></div></section></main></div>;
}
